routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('companies-auth.login');
});
Route::get('employees/login', function () {
    return view('employees-auth.login');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__.'/auth.php';
require __DIR__.'/companies.php';
require __DIR__.'/employees.php';

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

app/View/Components/CompaniesAppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class CompaniesAppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('companies-layouts.app');
    }
}

app/View/Components/EmployeesAppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class EmployeesAppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('employees-layouts.app');
    }
}

resources/views/companies-dashboard.blade.php
<x-companies-app-layout>
    @section('content')
    <div class="container mt-5">
        <div class="d-flex mt-5">
            <div class="card me-5" style="width: 18rem;">
                <div class="card-body">
                  <h5 class="card-title">Employees</h5>
                  <a href="{{ route('companies.employees.index') }}" class="card-link">Employees Listing</a>
                </div>
              </div>
              <div class="card" style="width: 18rem;">
                <div class="card-body">
                  <h5 class="card-title">Employees leaves</h5>
                  <a href="{{ route('companies.Companyindex') }}" class="card-link">Leaves</a>
                </div>
              </div>
        </div>
        
    </div>
    @endsection
</x-companies-app-layout>

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900">
                    {{ __("You're logged in!") }}
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/employees-dashboard.blade.php
<x-employees-app-layout>
    @section('content')
    <div class="container mt-5">
        <div class="d-flex mt-5">
            <div class="card me-5" style="width: 18rem;">
                <div class="card-body">
                  <h5 class="card-title">Employees</h5>
                  <a href="{{ route('companies.employees.index') }}" class="card-link">Employees Listing</a>
                </div>
              </div>
              <div class="card" style="width: 18rem;">
                <div class="card-body">
                  <h5 class="card-title">Employees leaves</h5>
                  <a href="{{ route('employees.employees-leaves.index') }}" class="card-link">Leaves</a>
                </div>
              </div>
        </div>
        
    </div>
    @endsection
</x-employees-app-layout>