routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('companies-auth.login');
});
Route::get('employees/login', function () {
    return view('employees-auth.login');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__.'/auth.php';
require __DIR__.'/companies.php';
require __DIR__.'/employees.php';

app/View/Components/EmployeesGuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class EmployeesGuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('employees-layouts.guest');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.guest');
    }
}

resources/views/employees-auth/login.blade.php
<x-employees-guest-layout>
    @section('content')
    <div class="container ">
        <div class="row justify-content-center mt-5">
            <div class="col-md-5 border-1 p-5 BorderStyle">
                <div>
                    <h3>Employee-Login</h3>
                </div>
                <form action="{{ route('employees.login') }}" method="POST" id="employeeLogin">
                    @csrf
                    <div class="mb-3">
                      <label  class="form-label">Email address</label>
                      <input type="email" name="email" class="form-control">
                      <x-input-error :messages="$errors->get('email')" class="mt-2" />
                    </div>
                    <div class="mb-3">
                      <label  class="form-label">Password</label>
                      <input type="password" name="password" class="form-control" >
                      <x-input-error :messages="$errors->get('password')" class="mt-2" />
                    </div>
                   <div class="d-flex">
                    <div class="me-2">
                        <a href="{{ route('companies.login') }}" >Companies Login</button>
                    </div>
                    <div class="me-2">
                        <a href="{{ route('companies.register') }}" >Companies Register</button>
                    </div>
                    <div>
                         <button type="submit" class="btn btn-sm btn-primary">Submit</button>
                    </div>
                   </div>
                </form>
            </div>
        </div>
       
    </div>
    @endsection
</x-employees-guest-layout>