routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('companies-auth.login');
});
Route::get('employees/login', function () {
    return view('employees-auth.login');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__.'/auth.php';
require __DIR__.'/companies.php';
require __DIR__.'/employees.php';

app/View/Components/CompaniesGuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class CompaniesGuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('companies-layouts.guest');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.guest');
    }
}

resources/views/companies-auth/login.blade.php
<x-companies-guest-layout>
    @section('content')
    <div class="container ">
        <div class="row justify-content-center mt-5">
            <div class="col-md-5 border-1 p-5 BorderStyle">
                <div>
                    <h3>Companies-Login</h3>
                </div>
                <form action="{{ route('companies.login') }}" method="POST" id="CompanyLogin">
                    @csrf
                    <div class="mb-3">
                      <label  class="form-label">Email address</label>
                      <input type="email" name="email" class="form-control">
                      <x-input-error :messages="$errors->get('email')" class="mt-2" />
                    </div>
                    <div class="mb-3">
                      <label  class="form-label">Password</label>
                      <input type="password" name="password" class="form-control" >
                      <x-input-error :messages="$errors->get('password')" class="mt-2" />
                    </div>
                   <div class="d-flex">
                    <div class="me-2">
                        <a href="{{ route('employees.login') }}" >Employee</button>
                    </div>
                    <div class="me-2">
                        <a href="{{ route('companies.register') }}" >Register</button>
                    </div>
                    <div>
                         <button type="submit" class="btn btn-sm btn-primary">Submit</button>
                    </div>
                   </div>
                </form>
            </div>
        </div>
       
    </div>
    @endsection
</x-companies-guest-layout>

resources/views/companies-auth/register.blade.php
{{-- <x-guest-layout>
    <form method="POST" action="{{ route('register') }}">
        @csrf

        <!-- Name -->
        <div>
            <x-input-label for="name" :value="__('Name')" />
            <x-text-input id="name" class="block mt-1 w-full" type="text" name="name" :value="old('name')" required autofocus autocomplete="name" />
            <x-input-error :messages="$errors->get('name')" class="mt-2" />
        </div>

        <!-- Email Address -->
        <div class="mt-4">
            <x-input-label for="email" :value="__('Email')" />
            <x-text-input id="email" class="block mt-1 w-full" type="email" name="email" :value="old('email')" required autocomplete="username" />
            <x-input-error :messages="$errors->get('email')" class="mt-2" />
        </div>

        <!-- Password -->
        <div class="mt-4">
            <x-input-label for="password" :value="__('Password')" />

            <x-text-input id="password" class="block mt-1 w-full"
                            type="password"
                            name="password"
                            required autocomplete="new-password" />

            <x-input-error :messages="$errors->get('password')" class="mt-2" />
        </div>

        <!-- Confirm Password -->
        <div class="mt-4">
            <x-input-label for="password_confirmation" :value="__('Confirm Password')" />

            <x-text-input id="password_confirmation" class="block mt-1 w-full"
                            type="password"
                            name="password_confirmation" required autocomplete="new-password" />

            <x-input-error :messages="$errors->get('password_confirmation')" class="mt-2" />
        </div>

        <div class="flex items-center justify-end mt-4">
            <a class="underline text-sm text-gray-600 hover:text-gray-900 rounded-md focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" href="{{ route('login') }}">
                {{ __('Already registered?') }}
            </a>

            <x-primary-button class="ms-4">
                {{ __('Register') }}
            </x-primary-button>
        </div>
    </form>
</x-guest-layout> --}}



<x-companies-guest-layout>
    @section('content')
    <div class="container ">
        <div class="row justify-content-center mt-5">
            <div class="col-md-5 border-1 p-5 BorderStyle">
                <div>
                    <h3>Companies-Register</h3>
                </div>
                <form action="{{ route('companies.register') }}" method="POST" id="regForm">
                    @csrf
                    <div class="mb-3">
                      <label  class="form-label">Name</label>
                      <input type="text" name="name" class="form-control">
                      <x-input-error :messages="$errors->get('name')" class="mt-2" />
                    </div>
                    <div class="mb-3">
                        <label  class="form-label">Email address</label>
                        <input type="email" name="email" class="form-control">
                        <x-input-error :messages="$errors->get('email')" class="mt-2" />
                      </div>
                    <div class="mb-3">
                      <label class="form-label">Password</label>
                      <input type="password" name="password" id="password" class="form-control" >
                      <x-input-error :messages="$errors->get('password')" class="mt-2" />
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Confirm Password</label>
                        <input type="password" name="password_confirmation" class="form-control" >
                        <x-input-error :messages="$errors->get('password_confirmation')" class="mt-2" />
                      </div>
                   <div class="d-flex">
                    <div class="me-2">
                        <a href="{{ route('companies.login') }}" >Login</button>
                    </div>
                    <div>
                         <button type="submit" class="btn btn-sm btn-primary">Submit</button>
                    </div>
                   </div>
                </form>
            </div>
        </div>
       
    </div>
    @endsection
</x-companies-guest-layout>